export const mockShelters = [
  {
    id: "tomi-taka001",
    name: "高岡市役所",
    name_kana: ["たかおかしやくしょ", "タカオカシヤクショ", "高岡市役所"],
    prefecture: "富山県",
    city: "高岡市",
    status: "開設中",
    capacity: 150,
    current_people: 15,
    stock_alert: true,
    orders: ["避難指示（高齢者）", "レベル3"],
    last_updated: "2025-05-22 00:00",
  },
  {
    id: "tomi-tomi000",
    name: "富山県庁",
    name_kana: ["とやまけんちょう", "トヤマケンチョウ", "富山県庁"],
    prefecture: "富山県",
    city: "富山市",
    status: "開設中",
    capacity: 300,
    current_people: 15,
    stock_alert: true,
    orders: ["避難指示（高齢者）", "レベル3"],
    last_updated: "2025-05-22 00:00",
  },
  {
    id: "tomi-tomi001",
    name: "富山市役所",
    name_kana: ["とやましやくしょ", "トヤマシヤクショ", "富山市役所"],
    prefecture: "富山県",
    city: "富山市",
    status: "開設中",
    capacity: 300,
    current_people: 15,
    stock_alert: false,
    orders: ["避難指示（高齢者）", "レベル3"],
    last_updated: "2025-05-22 00:00",
  }
];
