// 絞り込み用都道府県リスト
export const prefectures = [
  "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県",
  "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県",
  "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県",
  "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県",
  "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県",
  "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県",
  "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"
];

// 都道府県コード + 英語サブドメイン名付きリスト
export const separatedPrefectures = [
  { code: "01", name: "北海道", prefName: "hokkaido" },
  { code: "02", name: "青森県", prefName: "aomori" },
  { code: "03", name: "岩手県", prefName: "iwate" },
  { code: "04", name: "宮城県", prefName: "miyagi" },
  { code: "05", name: "秋田県", prefName: "akita" },
  { code: "06", name: "山形県", prefName: "yamagata" },
  { code: "07", name: "福島県", prefName: "fukushima" },
  { code: "08", name: "茨城県", prefName: "ibaraki" },
  { code: "09", name: "栃木県", prefName: "tochigi" },
  { code: "10", name: "群馬県", prefName: "gunma" },
  { code: "11", name: "埼玉県", prefName: "saitama" },
  { code: "12", name: "千葉県", prefName: "chiba" },
  { code: "13", name: "東京都", prefName: "tokyo" },
  { code: "14", name: "神奈川県", prefName: "kanagawa" },
  { code: "15", name: "新潟県", prefName: "niigata" },
  { code: "16", name: "富山県", prefName: "toyama" },
  { code: "17", name: "石川県", prefName: "ishikawa" },
  { code: "18", name: "福井県", prefName: "fukui" },
  { code: "19", name: "山梨県", prefName: "yamanashi" },
  { code: "20", name: "長野県", prefName: "nagano" },
  { code: "21", name: "岐阜県", prefName: "gifu" },
  { code: "22", name: "静岡県", prefName: "shizuoka" },
  { code: "23", name: "愛知県", prefName: "aichi" },
  { code: "24", name: "三重県", prefName: "mie" },
  { code: "25", name: "滋賀県", prefName: "shiga" },
  { code: "26", name: "京都府", prefName: "kyoto" },
  { code: "27", name: "大阪府", prefName: "osaka" },
  { code: "28", name: "兵庫県", prefName: "hyogo" },
  { code: "29", name: "奈良県", prefName: "nara" },
  { code: "30", name: "和歌山県", prefName: "wakayama" },
  { code: "31", name: "鳥取県", prefName: "tottori" },
  { code: "32", name: "島根県", prefName: "shimane" },
  { code: "33", name: "岡山県", prefName: "okayama" },
  { code: "34", name: "広島県", prefName: "hiroshima" },
  { code: "35", name: "山口県", prefName: "yamaguchi" },
  { code: "36", name: "徳島県", prefName: "tokushima" },
  { code: "37", name: "香川県", prefName: "kagawa" },
  { code: "38", name: "愛媛県", prefName: "ehime" },
  { code: "39", name: "高知県", prefName: "kochi" },
  { code: "40", name: "福岡県", prefName: "fukuoka" },
  { code: "41", name: "佐賀県", prefName: "saga" },
  { code: "42", name: "長崎県", prefName: "nagasaki" },
  { code: "43", name: "熊本県", prefName: "kumamoto" },
  { code: "44", name: "大分県", prefName: "oita" },
  { code: "45", name: "宮崎県", prefName: "miyazaki" },
  { code: "46", name: "鹿児島県", prefName: "kagoshima" },
  { code: "47", name: "沖縄県", prefName: "okinawa" },
];

export const prefMapping = {
  'cityriskview-hokkaido': '北海道',
  'cityriskview-aomori': '青森県',
  'cityriskview-iwate': '岩手県',
  'cityriskview-miyagi': '宮城県',
  'cityriskview-akita': '秋田県',
  'cityriskview-yamagata': '山形県',
  'cityriskview-fukushima': '福島県',
  'cityriskview-ibaraki': '茨城県',
  'cityriskview-tochigi': '栃木県',
  'cityriskview-gunma': '群馬県',
  'cityriskview-saitama': '埼玉県',
  'cityriskview-chiba': '千葉県',
  'cityriskview-tokyo': '東京都',
  'cityriskview-kanagawa': '神奈川県',
  'cityriskview-niigata': '新潟県',
  'cityriskview-toyama': '富山県',
  'cityriskview-ishikawa': '石川県',
  'cityriskview-fukui': '福井県',
  'cityriskview-yamanashi': '山梨県',
  'cityriskview-nagano': '長野県',
  'cityriskview-gifu': '岐阜県',
  'cityriskview-shizuoka': '静岡県',
  'cityriskview-aichi': '愛知県',
  'cityriskview-mie': '三重県',
  'cityriskview-shiga': '滋賀県',
  'cityriskview-kyoto': '京都府',
  'cityriskview-osaka': '大阪府',
  'cityriskview-hyogo': '兵庫県',
  'cityriskview-nara': '奈良県',
  'cityriskview-wakayama': '和歌山県',
  'cityriskview-tottori': '鳥取県',
  'cityriskview-shimane': '島根県',
  'cityriskview-okayama': '岡山県',
  'cityriskview-hiroshima': '広島県',
  'cityriskview-yamaguchi': '山口県',
  'cityriskview-tokushima': '徳島県',
  'cityriskview-kagawa': '香川県',
  'cityriskview-ehime': '愛媛県',
  'cityriskview-kochi': '高知県',
  'cityriskview-fukuoka': '福岡県',
  'cityriskview-saga': '佐賀県',
  'cityriskview-nagasaki': '長崎県',
  'cityriskview-kumamoto': '熊本県',
  'cityriskview-oita': '大分県',
  'cityriskview-miyazaki': '宮崎県',
  'cityriskview-kagoshima': '鹿児島県',
  'cityriskview-okinawa': '沖縄県',
};