// 絞り込み用都道府県リスト
export const prefectures = [
  "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県",
  "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県",
  "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県",
  "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県",
  "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県",
  "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県",
  "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"
];

// 都道府県コード + 英語サブドメイン名付きリスト
export const separatedPrefectures = [
  { code: "01", name: "北海道", prefName: "hokkaido" },
  { code: "02", name: "青森県", prefName: "aomori" },
  { code: "03", name: "岩手県", prefName: "iwate" },
  { code: "04", name: "宮城県", prefName: "miyagi" },
  { code: "05", name: "秋田県", prefName: "akita" },
  { code: "06", name: "山形県", prefName: "yamagata" },
  { code: "07", name: "福島県", prefName: "fukushima" },
  { code: "08", name: "茨城県", prefName: "ibaraki" },
  { code: "09", name: "栃木県", prefName: "tochigi" },
  { code: "10", name: "群馬県", prefName: "gunma" },
  { code: "11", name: "埼玉県", prefName: "saitama" },
  { code: "12", name: "千葉県", prefName: "chiba" },
  { code: "13", name: "東京都", prefName: "tokyo" },
  { code: "14", name: "神奈川県", prefName: "kanagawa" },
  { code: "15", name: "新潟県", prefName: "niigata" },
  { code: "16", name: "富山県", prefName: "toyama" },
  { code: "17", name: "石川県", prefName: "ishikawa" },
  { code: "18", name: "福井県", prefName: "fukui" },
  { code: "19", name: "山梨県", prefName: "yamanashi" },
  { code: "20", name: "長野県", prefName: "nagano" },
  { code: "21", name: "岐阜県", prefName: "gifu" },
  { code: "22", name: "静岡県", prefName: "shizuoka" },
  { code: "23", name: "愛知県", prefName: "aichi" },
  { code: "24", name: "三重県", prefName: "mie" },
  { code: "25", name: "滋賀県", prefName: "shiga" },
  { code: "26", name: "京都府", prefName: "kyoto" },
  { code: "27", name: "大阪府", prefName: "osaka" },
  { code: "28", name: "兵庫県", prefName: "hyogo" },
  { code: "29", name: "奈良県", prefName: "nara" },
  { code: "30", name: "和歌山県", prefName: "wakayama" },
  { code: "31", name: "鳥取県", prefName: "tottori" },
  { code: "32", name: "島根県", prefName: "shimane" },
  { code: "33", name: "岡山県", prefName: "okayama" },
  { code: "34", name: "広島県", prefName: "hiroshima" },
  { code: "35", name: "山口県", prefName: "yamaguchi" },
  { code: "36", name: "徳島県", prefName: "tokushima" },
  { code: "37", name: "香川県", prefName: "kagawa" },
  { code: "38", name: "愛媛県", prefName: "ehime" },
  { code: "39", name: "高知県", prefName: "kochi" },
  { code: "40", name: "福岡県", prefName: "fukuoka" },
  { code: "41", name: "佐賀県", prefName: "saga" },
  { code: "42", name: "長崎県", prefName: "nagasaki" },
  { code: "43", name: "熊本県", prefName: "kumamoto" },
  { code: "44", name: "大分県", prefName: "oita" },
  { code: "45", name: "宮崎県", prefName: "miyazaki" },
  { code: "46", name: "鹿児島県", prefName: "kagoshima" },
  { code: "47", name: "沖縄県", prefName: "okinawa" },
];
